import type { AppState } from "./types";

export const industries = [
  "互联网/IT",
  "产品/项目",
  "运营/客服",
  "销售/市场",
  "设计/传媒",
  "人事/行政",
  "财务/法务",
  "供应链/物流",
  "制造/工厂",
  "建筑/地产",
  "医疗/教育",
  "金融/保险",
  "服务业",
  "政企/公共服务",
  "电商/直播",
  "餐饮/门店",
  "家政/生活服务",
  "农业/能源",
  "实习/应届"
];

export const rolesByIndustry: Record<string, string[]> = {
  "互联网/IT": ["前端开发", "后端开发", "测试工程师", "数据分析师", "运维工程师", "Java开发", "Python开发", "实施工程师", "技术支持", "网络安全"],
  "产品/项目": ["产品经理", "项目经理", "实施顾问", "需求分析师", "项目助理", "PMO", "交付经理", "解决方案顾问"],
  "运营/客服": ["用户运营", "内容运营", "电商运营", "客服主管", "社群运营", "客服专员", "客服运营", "活动运营", "数据运营", "商家运营"],
  "销售/市场": ["销售顾问", "大客户销售", "渠道销售", "市场专员", "品牌策划", "商务BD", "电话销售", "销售经理", "市场活动", "客户成功"],
  "设计/传媒": ["UI设计师", "平面设计师", "视频剪辑", "新媒体编辑", "短视频编导", "文案策划", "摄影摄像", "品牌设计"],
  "人事/行政": ["招聘专员", "HRBP", "行政主管", "薪酬绩效", "人事专员", "员工关系", "培训专员", "行政前台"],
  "财务/法务": ["会计", "财务分析", "审计", "法务专员", "出纳", "税务专员", "成本会计", "合同管理"],
  "供应链/物流": ["采购专员", "物流调度", "仓储主管", "供应链计划", "外贸跟单", "订单管理", "运输调度", "库存管理"],
  "制造/工厂": ["生产主管", "质量工程师", "设备工程师", "工艺工程师", "普工/操作工", "质检员", "生产计划", "班组长"],
  "建筑/地产": ["工程资料员", "施工员", "造价员", "招商运营", "物业管家", "置业顾问", "工程监理", "安全员"],
  "医疗/教育": ["课程顾问", "教务管理", "护士", "医药代表", "教师", "助教", "康复治疗师", "医疗客服"],
  "金融/保险": ["客户经理", "风控专员", "理财顾问", "保险顾问", "信贷专员", "催收专员", "柜员", "金融销售"],
  "服务业": ["门店店长", "前厅主管", "旅游顾问", "物业管家", "酒店前台", "美容顾问", "健身顾问", "收银员"],
  "政企/公共服务": ["政企客户经理", "公共事务", "社区运营", "综合文员", "网格员", "政务热线", "档案管理", "窗口服务"],
  "电商/直播": ["电商运营", "直播运营", "主播", "中控", "选品专员", "短视频运营", "投流专员", "客服转运营"],
  "餐饮/门店": ["店员", "店长", "餐厅主管", "茶饮店长", "后厨主管", "区域督导", "收银员", "营运督导"],
  "家政/生活服务": ["家政顾问", "育婴师", "养老护理", "保洁主管", "维修调度", "生活服务客服", "门店顾问"],
  "农业/能源": ["农产品销售", "养殖技术员", "新能源销售", "光伏运维", "设备巡检", "安全员", "项目协调"],
  "实习/应届": ["运营实习生", "产品助理", "行政助理", "销售助理", "数据助理", "测试助理", "新媒体助理", "招聘助理"]
};

export const assessmentQuestions = [
  { id: "q1", dimension: "communication", text: "过去半年里，需要和陌生同事或客户对齐信息时，我通常能主动问清需求并推动下一步。" },
  { id: "q2", dimension: "communication", text: "当任务涉及多人协作时，我能接受反复确认、提醒进度和同步信息。" },
  { id: "q3", dimension: "stability", text: "只要目标和标准清楚，我可以稳定完成一段时间的重复性工作。" },
  { id: "q4", dimension: "stability", text: "和每天临时救火相比，我更容易在节奏稳定、规则清楚的环境里发挥。" },
  { id: "q5", dimension: "pressure", text: "时间紧、任务多时，我通常会先排序，再处理最关键的事情。" },
  { id: "q6", dimension: "pressure", text: "被指出问题时，我多数情况下能先确认事实和修正动作，再处理情绪。" },
  { id: "q7", dimension: "detail", text: "交付前，我会检查关键细节，尽量避免低级错误影响结果。" },
  { id: "q8", dimension: "detail", text: "如果一件事以后还会重复，我愿意整理文档、模板或数据记录。" },
  { id: "q9", dimension: "learning", text: "为了拿到目标岗位，我能连续几周安排固定时间学习或练习。" },
  { id: "q10", dimension: "learning", text: "遇到不熟悉的工具或业务，我通常会先查资料、试一遍，再判断是否适合继续学。" },
  { id: "q11", dimension: "result", text: "描述工作成果时，我会尽量说清数量、周期、效率、转化或交付物。" },
  { id: "q12", dimension: "result", text: "如果工作只看过程、不看结果，我会需要额外确认最终评价标准。" },
  { id: "q13", dimension: "communication", text: "意见不一致时，我通常会先确认对方目标，再表达自己的判断。" },
  { id: "q14", dimension: "communication", text: "向上汇报、跨部门催进度、对外解释问题这些沟通任务，我可以承担一部分。" },
  { id: "q15", dimension: "stability", text: "短期看不到明显成果时，我仍能按计划推进一段时间，而不是马上放弃。" },
  { id: "q16", dimension: "stability", text: "如果岗位长期高度混乱、规则经常变化，我的消耗会明显增加。" },
  { id: "q17", dimension: "pressure", text: "面对业绩、投诉或截止日期压力时，我能把压力拆成可执行的下一步。" },
  { id: "q18", dimension: "pressure", text: "连续出现突发问题时，我还能保持基本判断，但可能需要更清楚的优先级。" },
  { id: "q19", dimension: "detail", text: "我愿意记录关键过程或沉淀模板，以减少后续重复沟通和返工。" },
  { id: "q20", dimension: "detail", text: "岗位要求流程、数据、文档和严谨交付时，我不会明显排斥。" },
  { id: "q21", dimension: "learning", text: "为了转岗或升职，我愿意用作品、证书、试岗任务来补充能力证明。" },
  { id: "q22", dimension: "learning", text: "如果目标岗位暂时够不到，我可以考虑先从低一级或过渡岗位切入。" },
  { id: "q23", dimension: "result", text: "做完一件事后，我会复盘哪些动作有效、哪些无效，而不只等待别人评价。" },
  { id: "q24", dimension: "result", text: "岗位目标不清楚时，我会尝试拆出阶段性结果或先问清评价标准。" }
] as const;

export const answerOptions = [
  { value: 1, label: "非常不符合" },
  { value: 2, label: "不太符合" },
  { value: 3, label: "一般" },
  { value: 4, label: "比较符合" },
  { value: 5, label: "非常符合" }
];

export const defaultState: AppState = {
  role: "jobseeker",
  detailMode: "quick",
  studentProfile: {
    grade: "大三/研二，开始找实习",
    major: "暂不确定/想让系统结合课程和兴趣判断",
    graduationTime: "一年内毕业",
    schoolLevel: "普通本科/大专/高职",
    hasInternship: "没有正式实习",
    campusExperience: "暂无，后续填写课程、社团、班委、校园活动或志愿经历",
    courseProjects: "暂无，后续补充课程大作业、毕设、论文、调研报告或作品",
    competitions: "暂无竞赛/证书",
    partTimeExperience: "暂无兼职/校园推广/家教/门店经历",
    certificates: "暂无证书",
    portfolio: "还没有作品集",
    firstJobPreference: "先找能入门、能积累经验的岗位",
    cityBudget: "预算有限，优先低成本城市或家附近",
    familySupport: "家里能支持一段时间，但希望尽快就业"
  },
  careerIntent: {
    clarity: "还不明确，只知道想要更合适的工作",
    mainGoal: "涨薪||减少加班||获得成长和晋升",
    expectedIncome: "10k-15k",
    bottomLine: "长期高强度加班||通勤超过60分钟||收入波动大",
    preferredWorkStyle: "稳定清晰的流程||数据分析和复盘||目标明确按结果评价",
    avoidWork: "纯电话销售||长期夜班倒班||没有成长空间",
    strengths: "执行力||学习快||数据分析",
    weakPoints: "简历不会写||没有量化成果||目标不明确",
    companyPreference: "中小公司但成长快||互联网/科技公司||不挑公司，先就业",
    roleLevelPreference: "有经验专员",
    learningBudget: "每天1小时左右",
    jobSearchObstacle: "不知道适合做什么||简历没有亮点",
    cityPreference: "优先当前城市，也可以听建议评估其他城市",
    transitionOpenness: "可以接受过渡岗位，但希望能靠近长期方向",
    marketValidation: "暂未验证；建议在招聘软件搜索目标城市+岗位，记录岗位数量、薪资区间、常见要求和通勤区域。"
  },
  profile: {
    name: "游客用户",
    city: "上海",
    cityArea: "浦东/徐汇/静安",
    education: "本科",
    years: "1-3年",
    status: "在职看机会",
    targetSalary: "10k-15k",
    urgency: "1-2个月内找到更好",
    familyContext: "",
    flexibility: ["接受加班强度适中", "接受跨行业转岗"],
    wantsManagement: "暂时不强求管理，更希望先把专业能力做扎实",
    hasCareDuty: "无固定照护责任",
    canRelocate: "暂不考虑跨城市",
    commuteLimit: "单程 60 分钟以内",
    overtimeTolerance: "可接受阶段性加班，不接受长期高强度",
    travelTolerance: "可接受偶尔出差"
  },
  experiences: [
    {
      company: "示例公司",
      title: "运营专员",
      period: "2022.06 - 至今",
      highlights: "负责用户社群运营、活动策划和数据复盘，曾将活动参与率从12%提升到27%。"
    }
  ],
  assessment: {
    communication: 70,
    stability: 70,
    pressure: 70,
    detail: 70,
    learning: 70,
    result: 70
  },
  assessmentAnswers: {
    q1: 4,
    q2: 4,
    q3: 4,
    q4: 3,
    q5: 4,
    q6: 3,
    q7: 4,
    q8: 4,
    q9: 5,
    q10: 4,
    q11: 4,
    q12: 4,
    q13: 4,
    q14: 3,
    q15: 4,
    q16: 4,
    q17: 3,
    q18: 3,
    q19: 4,
    q20: 4,
    q21: 5,
    q22: 4,
    q23: 4,
    q24: 4
  },
  targetJob: {
    industry: "运营/客服",
    role: "用户运营",
    city: "上海",
    cityArea: "浦东新区/徐汇区/杨浦区",
    jd: "负责用户增长、社群维护、活动策划、数据复盘，要求有用户沟通经验、执行力和基础数据分析能力。",
    managementLevel: "不需要直接带人",
    workIntensity: "节奏中等，偶尔加班",
    travelRequirement: "不需要出差",
    cityOpportunity: "目标城市机会一般",
    incomeStability: "收入相对稳定",
    marketValidation: "上海用户运营：岗位较多，常见要求为社群/活动/数据复盘，薪资多集中在10k-18k，核心区域在浦东、徐汇、杨浦。"
  },
  resumeDraft:
    "负责用户社群维护、线上活动执行、用户反馈整理和数据报表制作。熟悉活动策划流程，具备基础数据分析能力。",
  recruiterJob: {
    company: "示例科技有限公司",
    title: "用户运营",
    department: "增长运营部",
    salary: "12k-18k",
    hiringReason: "新增岗位，承担用户增长和留存目标",
    workMode: "坐班，偶尔加班",
    teamStructure: "向运营负责人汇报，与产品、客服、市场协作",
    coreTasks: "用户分层运营；社群维护；活动策划执行；用户反馈闭环；数据复盘",
    successMetrics: "活动参与率、用户留存、社群活跃、转化率、反馈处理时效",
    jd: "负责用户分层运营、社群增长、活动转化和数据复盘，需要良好的沟通能力、执行力和跨部门协作能力。",
    mustHave: "有用户运营、社群运营或活动运营经验；能用数据复盘结果；沟通主动。",
    softSkills: "沟通主动；执行稳定；愿意复盘；能承受阶段性活动压力",
    dealBreakers: "完全没有用户/客服/运营相关经历；不能接受活动期加班；不愿意看数据",
    redFlags: "只做过机械执行、没有数据意识、不能接受阶段性活动加班。",
    sellingPoints: "业务增长快、岗位有明确晋升路径、团队愿意带新人。",
    searchKeywords: "用户运营 社群 活动 数据复盘 增长 留存",
    candidateResume:
      "候选人A｜3年用户运营经验，负责社群活动、用户反馈和数据复盘，活动参与率提升27%。\n---\n候选人B｜2年客服经验，熟悉用户沟通和投诉处理，数据复盘较少。\n---\n候选人C｜电商运营助理，负责活动报名、商品维护和报表整理，有基础Excel能力。",
    screeningPriority: "优先匹配硬性门槛，再看成果证据"
  },
  aiConfig: {
    apiKey: "",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4.1-mini",
    allowSensitiveAi: false
  }
};
